INPUT=~/src/lilypond/build/

all:
	@echo "Do you want to \"make import\" to get updated bib itexi?"
	@echo "if so, remember to change the INPUT env var (if necessary)"

import:
	cp ${INPUT}/Documentation/out/others-did.itexi .
	cp ${INPUT}/Documentation/out/we-wrote.itexi .
