\input texinfo

@node Top
@top Grand Organization Project - Policy Proposals (GOP-PROP)
@settitle LilyPond GOP-PROP 

@macro late{TEXT}
@cartouche
@strong{Addition after "probable decision":} \TEXT\

@end cartouche

@end macro

@macro qq{TEXT}
@quotedblleft{}\TEXT\@quotedblright{}
@end macro



There are a number of policy decisions -- some of them fairly
important -- which we have been postponing for a few years.  Now
that 2.14 is out, we will finally begin tackling them.

More background is here:
@uref{http://lilypond.org/doc/v2.15/Documentation/contributor/policy-decisions}

@subheading Meta-policies

To summarize and/or hopefully avoid useless fluffy discussions:

@itemize
@item
Topics will be introduced by Graham.  He will put an agenda for
the next month (or so) on @uref{http://lilypond.org/~graham/gop/}

@item
We will @strong{only} seriously discuss topics when we have
adequate background research.

@item
Emails about policy questions will begin with @code{GOP-PROP} in
the subject line.  Adjust your email filters accordingly,
depending on whether you are interested or not in such
discussions.

@item
There should be no surprises, no time pressure, etc.  If you are
particularly concerned about a decision but lack time/energy to
join the discussion, just say so and we will postponed the
decision.  I want to have clear, final, unambiguous decisions; if
that takes a long time, so be it.

@item
For each policy question, there will be at least @strong{one week}
for free-ranging discussion.  At that point, Graham will summarize
the discussion and announce a "probable decision".  We will then
have @strong{one more week} to let people point out flaws in the
summary, make additional arguments, etc.

@end itemize


@subheading Agenda

@multitable @columnfractions .05 .2 .2 .2
@headitem Date
  @tab Introduce policy question (-1d)
  @tab Summary and @qq{probable decision} (0d)
  @tab Implement decision (+1d)

@item
201-06-13
@tab
@ref{GOP2-0 - why are we losing developers?}
@tab @tab

@item
201-06-20
@tab
@tab
@tab

@item
201-06-27
@tab
@tab
@tab


@end multitable


@menu
* GOP2-0 - why are we losing developers?::
* GOP2-1 - LilyPond is part of GNU::
* GOP2-2 - Stable releases and roadmap (radical change)::
@end menu


@node GOP2-0 - why are we losing developers?
@chapter GOP2-0 - why are we losing developers?

FIXME: add link to initial email



@node GOP2-1 - LilyPond is part of GNU
@chapter GOP2-1 - LilyPond is part of GNU



@multitable @columnfractions .33 .1 .33

@headitem Requirement
  @tab Source
  @tab Implications for lilypond

@item
All authors of more than 15 lines of code need to be listed in the
file headers
@tab
6.2
@tab
Not in compliance; hopefully we can automate this process to some
degree with git?



@end multitable



@node GOP2-2 - Stable releases and roadmap (radical change)
@chapter GOP2-2 - Stable releases and roadmap (radical change)



@bye

