\input texinfo

@node Top
@top Grand Organization Project - Policy Proposals (GOP-PROP)
@settitle LilyPond GOP-PROP 

@macro late{TEXT}
@cartouche
@strong{Addition after "probable decision":} \TEXT\

@end cartouche

@end macro

@macro qq{TEXT}
@quotedblleft{}\TEXT\@quotedblright{}
@end macro



There are a number of policy decisions -- some of them fairly
important -- which we have been postponing for a few years.  Now
that 2.14 is out, we will finally begin tackling them.

More background is here:
@uref{http://lilypond.org/doc/v2.15/Documentation/contributor/policy-decisions}

@subheading Meta-policies

To summarize and/or hopefully avoid useless fluffy discussions:

@itemize
@item
Topics will be introduced by Graham.  He will put an agenda for
the next month (or so) on @uref{http://lilypond.org/~graham/gop/}

@item
We will @strong{only} seriously discuss topics when we have
adequate background research.

@item
Emails about policy questions will begin with @code{GOP-PROP} in
the subject line.  Adjust your email filters accordingly,
depending on whether you are interested or not in such
discussions.

@item
There should be no surprises, no time pressure, etc.  If you are
particularly concerned about a decision but lack time/energy to
join the discussion, just say so and we will postponed the
decision.  I want to have clear, final, unambiguous decisions; if
that takes a long time, so be it.

@item
For each policy question, there will be at least @strong{one week}
for free-ranging discussion.  At that point, Graham will summarize
the discussion and announce a "probable decision".  We will then
have @strong{one more week} to let people point out flaws in the
summary, make additional arguments, etc.

@end itemize


@subheading Agenda

@multitable @columnfractions .05 .2 .2 .2
@headitem Date
  @tab Introduce policy question (-1d)
  @tab Summary and @qq{probable decision} (0d)
  @tab Implement decision (+1d)

@item
201-06-13
@tab
@ref{GOP2-0 - why are we losing developers?}
@tab @tab

@item
201-06-20
@tab
@tab
@tab

@item
201-06-27
@tab
@tab
@tab


@end multitable


@menu
* GOP2-0 - why are we losing developers?::
* GOP2-1 - LilyPond is part of GNU::
* GOP2-2 - Stable releases and roadmap (radical change)::
@end menu


@node GOP2-0 - why are we losing developers?
@chapter GOP2-0 - why are we losing developers?

Survey sent:

@example
@uref{http://lists.gnu.org/archive/html/lilypond-devel/2012-06/msg00192.html}
@end example



@node GOP2-1 - LilyPond is part of GNU
@chapter GOP2-1 - LilyPond is part of GNU

@heading Summary

intro blurb

@example
@uref{http://www.gnu.org/prep/maintain/maintain.html}
@end example

I've separated these into project Requirements, project Strongly
Recommended, and Suggested.  I've also created a list of
maintainer Requirements and Suggested.


@heading Project Requirements

@multitable @columnfractions .33 .1 .33

@headitem Requirement
  @tab Source
  @tab Implications for lilypond

@item
All authors of more than 15 lines of code need to be listed in the
file headers
@tab
6.2
@tab
@c Not in compliance; hopefully we can automate this process to
@c some degree with git?


@item
All features must work on GNU/Linux; other operating systems are
optional
@tab
8
@tab


@item
keep backups of source files, but git is sufficient for this
@tab
10
@tab


@item
on self-hosted websites, ensure that the site runs on Free
software alone.  (unreleased custom software is ok)
@tab
12.2
@tab


@item
don't link to a website about lilypond, which the public
might perceive as connected with it and reflecting the position of
its developers, unless it also runs on free software.
@tab
12.2
@tab


@item
avoid patented technologies as specified by GNU.  For example,
mp3.
@tab
13
@tab


@item
do not recommend any non-Free programs, nor require a non-free
program to build
@tab
13
@tab

@item
do not refer to any non-Free documentation for Free software
@tab
13
@tab

@item
do not use the term @qq{open source}, instead of @qq{Free
software}
@tab
14.1
@tab

@item
do not write @qq{Linux}, instead write @qq{GNU/Linux} (unless we
are specifically talking about the kernel)
@tab
14.2
@tab

@end multitable


@heading Project Strongly recommended

@multitable @columnfractions .33 .1 .33

@headitem Requirement
  @tab Source
  @tab Implications for lilypond

@item
@tab
@tab

@end multitable



@heading foo

@multitable @columnfractions .33 .1 .33

@headitem Requirement
  @tab Source
  @tab Implications for lilypond

@item
@tab
@tab

@item
@tab
@tab

@end multitable




@node GOP2-2 - Stable releases and roadmap (radical change)
@chapter GOP2-2 - Stable releases and roadmap (radical change)



@bye

